ITL-1-Basic API for ToDoList with errors and CRUD methods
Barabasbalazs/ToDoListAPI pull request #1
Opened 2023-02-15 09:37 UTC by Barabasbalazs

2023-02-15 10:01 UTC, roli-wg requested changes

2023-02-15 10:01 UTC, roli-wg commented on src/models/todo-model.ts
> +  title: { type: string; required: true };
Using interfaces every field is required by default you don't have to explicitly specify

2023-02-15 10:01 UTC, roli-wg commented on src/routes/todos/todo-controller.ts
> +    res: Response,
Is a good practice to specify also the Response type `Response<Todo>`

2023-02-15 10:01 UTC, roli-wg commented on src/routes/todos/todo-controller.ts
> +  getAllToDos: async (req: Request, res: Response, next: NextFunction) => {
Try to keep the naming simple you are inside the todoController so you don't need to add todo/todos as sufix for your methods 
You can name just save, getAll, getById...

2023-02-15 10:01 UTC, roli-wg commented on src/routes/todos/todo-controller.ts
> +      console.log(req.params._id);
Please remove all console.log

2023-02-15 10:01 UTC, roli-wg commented on src/services/todo-service.ts
> +  insertToDo: async (toDo: ToDo): Promise<ToDo | void> => {
Pay attention to naming here as well

2023-02-15 10:01 UTC, roli-wg commented on src/services/todo-service.ts
> +      returnOriginal: false,
use `new:true` as option for update to return the updated document

2023-02-15 13:28 UTC, roli-wg approved these changes

2023-02-16 11:23 UTC, SzaszWebgurus commented on src/index.ts
> +const port = process.env.PORT;
add default value

2023-02-16 11:33 UTC, merged