ITL-2-Add-validation
Barabasbalazs/ToDoListAPI pull request #2
Opened 2023-02-16 11:38 UTC by Barabasbalazs

2023-02-16 11:59 UTC, roli-wg requested changes

2023-02-16 11:59 UTC, roli-wg commented on src/middleware/validation.ts
> +      return next(errors.invalidParameter("Invalid ToDo"));
Please try to return more explanatory error messages, which is the first wrong field
Like "Missing or invalid parameter 'title'"

2023-02-16 11:59 UTC, roli-wg commented on src/middleware/validation.ts
> +    return next(errors.invalidParameter("Invalid parameters"));
Please pay attention to error message here as well

2023-02-16 11:59 UTC, roli-wg commented on src/routes/todos/todo-controller.ts
> +      const searchString = req.query.search;
You can destructor the req.query object to define this variables in one line
`const { sortBy, order, searchString } = req.query`

2023-02-16 11:59 UTC, roli-wg commented on src/services/todo-service.ts
> +    }
What if we want to search and sort in the same time, please rewrite this to support search and sort simultaneously

2023-02-17 07:26 UTC, roli-wg approved these changes

2023-02-17 09:20 UTC, komaromiGyorgy approved these changes

2023-02-17 09:20 UTC, komaromiGyorgy commented on src/routes/todos/todo-controller.ts
> +      { sort?: keyof ToDo; order?: OrderType; search?: string }
Can you make just create types for these? This looks gnarly wherever you have query requests, for example you could do: 

`
export interface QueryRequest<T extends { [queryParam: string]: string; }> extends Request {
    query: T
}
export interface BodyRequest<T> extends Request {
    body: T
}
export interface ParamRequest<T extends { [param: string]: string; [captureGroup: number]: string; }> extends Request {
    params: T
}

export function requesting(request: QueryRequest<ListRequest>) {
  request.query.order
}
`

2023-02-17 09:45 UTC, SzaszWebgurus requested changes

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/index.ts
> +const port = process.env.PORT ? process.env.PORT : 8080;
const port = process.env.PORT || 8080

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/middleware/validation.ts
> +        const errorReport = e as ErrorReport;
can you do this inline?

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/middleware/validation.ts
> +      const order = req.query.order;
const { sortBy, order} = req.query;

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/routes/todos/todo-controller.ts
> +      const id = req.params.id;
use general `validateId` DTO

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/routes/todos/todo-controller.ts
> +      if (!id) {
same as above

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/routes/todos/todo-router.ts
> +todoRouter.patch(
put

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/routes/todos/todo-router.ts
> +  todoController.update
updateOne

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/services/todo-service.ts
> +            { title: { $regex: searchString } },
use the regex in case insensitive mode

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/services/todo-service.ts
> +      stages.unshift({ $match: { title: { $regex: "/*" } } });
TODO: remove this <- add this comment

2023-02-17 09:45 UTC, SzaszWebgurus commented on src/services/todo-service.ts
> +      return await model.aggregate(stages).sort({ [sortBy]: order });
add the sort to the aggregation pipeline

2023-02-17 13:38 UTC, SzaszWebgurus approved these changes

2023-02-17 13:42 UTC, merged